### PR TITLE
Add OpenEmbedded helper target

### PR DESCRIPTION
**Pull request by tmagik**
Add a helper target to build openembedded.

This needs to be updated to point to public SiFive repos for meta-sifive{-dev}, meta-riscv, and meta-games for a release.

8/13 changes/known issues
* added 'make sdk' target
* clean checkout still runs buildroot
* need to lock kernel version(s)
* do we want to mirror everything that do_fetch grabs???

### CODE REVIEW

**Comment by davidlt** [comment]
I don't know how OE LDFLAGS would affect coremark right now (or in the future) thus the QA warning.

**Comment by paul-walmsley-sifive** [comment]
We should just replace the existing freedom-u-sdk with the OE-based build, after tagging the commit prior to the removal.  There's no point in continuing to support the old stuff any more.

**Comment by tmagik** [comment]
> On Aug 13, 2019, at 9:06 AM, Paul Walmsley <notifications@github.com> wrote:
> 
> We should just replace the existing freedom-u-sdk with the OE-based build, after tagging the commit prior to the removal. There's no point in continuing to support the old stuff any more.
> 

Until we have the same/similar functionality in an OE build, we’re going to end up supporting the ‘old’ buildroot system for customers even if we remove the old targets, so I am hesitant to remove it without having the important functionality working in OE.

Here’s a short (non-exhaustive) list of stuff that is probably important:

* make qemu  ( translates to bitbake runqemu, which needs to be implemented) 
* an initramfs image that can be written to the SPI flash and/or SDcard, capable of writing the SPI flash from linux (needs the ‘flashcp’ command)
* replacement for ‘make format-demo-image’ that builds an SDcard image that boots X11, SuperTuxKart, and other games/etc
* replace or document how to do what ‘make kernel-modules-install’ does

**Comment by paul-walmsley-sifive** [comment]
We never supported freedom-u-sdk in the first place.  So it should be enough to just take a branch with the old stuff, just as what was done with v1_0.   Then if someone wants to spend their time adding to that branch, they can do it there.

Regarding the requirements for what's needed from OE/Yocto, those need to be cleared through the product team (Drew specifically)

**Comment by tprrt** [comment]
This issue is no longer relevant.

**Pull request closed without merging**
