### PR TITLE
Added dhrystone, lmbench, screen and htop

### PR DESCRIPTION
**Pull request by solomatnikov**

### CODE REVIEW

**Comment by palmer-dabbelt** [comment]
Does this make the initramfs more than 16MiB?  It needs to stay somewhat small for the FPGA.

**Comment by solomatnikov** [comment]
Here are the size before and after:

```
-rwxrwxr-x 1 sols sols 12806308 Jan 24 17:26 ./__freedom-u-sdk/work/bbl.bin
-rwxrwxr-x 1 sols sols 15149220 Jan 26 19:03 ./_freedom-u-sdk/work/bbl.bin
```

So, it is still < 16 MB

Why is there such a low limit for the FPGA? It's hard to find flash chip which is that small.

**Comment by solomatnikov** [comment]
Of course, all of these are optional, I'd rather have perf compiled in.

**Comment by palmer-dabbelt** [comment]
sdboot only loads the first 16MiB from the SD card.

**Pull request merged**
