### PR TITLE
browser: Add the browser Chromium.

### PR DESCRIPTION
**Pull request by tingsi5**
Add the recipe for Chromium and include it in xfce4 image. There'll be a "Chromium Browser" under “Applications > Internet".

### CODE REVIEW

**Comment by nylon7** [comment]
Hi @Ruinland-Tsai @tprrt .
Will we need this feature?

**Comment by Ruinland-Tsai** [comment]
@tingsi5 
I am wondering how much optimization work we have put into this ?
It seems upstream Chromium is now having RISC-V 64 support.

If this PR is purely for architecture enablement, maybe we can switch to use the upstream version of Chromium.

**Comment by tingsi5** [comment]
Yes, this is basically for Chromium enablement on RISC-V. But we have turned away to different topics, and this is probably priority low now.

@GreenWanS5 Is my understanding correct? Do we still want to put any effort on this?

**Review by tprrt — CHANGES_REQUESTED** [review]
No longer seems necessary

**Comment by tingsi5** [comment]
I think yes, as it has be a while that we have no activities on this.

**Pull request closed without merging**
