### PR TITLE
Linux config for U500 VC707 FPGA Dev Kit, no graphics card

### PR DESCRIPTION
**Pull request by henrystyles**
Restore Linux build configuration file for U500 VC707 Dev Kit

### CODE REVIEW

**Comment by jim-wilson** [comment]
FYI after some experimenting with the linux_microsemi_distro_defconfig file, I discovered that I had to add

# CONFIG_VT is not set
CONFIG_SERIAL_8250=y
CONFIG_SERIAL_8250_CONSOLE=y
# CONFIG_SERIAL_8250_PCI is not set
CONFIG_SERIAL_OF_PLATFORM=y
CONFIG_SERIAL_SIFIVE=y
CONFIG_SERIAL_SIFIVE_CONSOLE=y
CONFIG_HVC_RISCV_SBI=y
CONFIG_VIRTIO_CONSOLE=y

to get the serial console working.  The CONFIG_VT line was non-obvious.  The rest of it was pretty obvious.  I haven't tried this on hardware yet, just spike so far.  That may not be a minimal change.  I just pulled all of the serial/console stuff in as it seemed related and obviously needed.  I do know that the CONFIG_VT line is required; it won't work without it.

The CONFIG_HVC_RISCV_SBI line enables the old serial driver, which is required by spike, and by pre-production unleashed boards.  I don't know about the vc707, this line might be optional there.  Most current configs explicitly turn this off to get the new serial driver.

**Comment by terpstra** [comment]
The problem is the DTS on the vc707 was incompatible with the current linux kernel tree. I'm working on fixing it still..

**Comment by terpstra** [comment]
We should not need a new config once I get the FPGA to create the right DTS.

**Comment by tprrt** [comment]
This issue is no longer relevant.

**Pull request closed without merging**
