### PR TITLE
Bump riscv-qemu to upstream v8

### PR DESCRIPTION
**Pull request by michaeljclark**
This bumps riscv-qemu to the version that supports SMP with MTTCG enabled.

e.g.

```
-smp cpus=4
```

### CODE REVIEW

**Comment by jim-wilson** [comment]
Using upstream v5 qemu breaks 32-bit support.  The stat syscall doesn't work correctly.  This may be a qemu problem or a glibc problem.  Of course, we may not care about 32-bit support in freedom-u-sdk.

See https://github.com/riscv/riscv-gnu-toolchain/pull/325 for more info.

**Comment by michaeljclark** [comment]
I can try and see what is happening with stat on rv32.

The version currently linked to freedom-u-sdk is based on 27-Sep-2016 upstream qemu (before our first rebase in December) and doesn't having working SMP, whereas v6 is based on the 10-Jan-2017 rebase which has working SMP and MTTCG.

- riscv-qemu-20180207
- riscv-qemu-20180110
- riscv-qemu-20171222
- riscv-qemu-20160927

It's likely we broke rv32 stat when we rebased on 22-Dec-2017 as there were a lot of changes to linux-user in the intervening year...

**Comment by michaeljclark** [comment]
The bullet points are tags, i.e. the dates the code was rebased against qemu master, and include the patch series and subsequent changes and backports.

**Comment by michaeljclark** [comment]
We apparently have the asm-generic versions, except !TARGET_RISCV64 (RV32) excludes TARGET_HAS_STRUCT_STAT64. The stat code has had quite a few changes. I copied the exclusion from the earlier qemu port. Perhaps that is the problem. Perhaps we should define stat64 on RV32

```
#elif defined(TARGET_OPENRISC) || defined(TARGET_TILEGX) || \
      defined(TARGET_NIOS2) || defined(TARGET_RISCV)

/* These are the asm-generic versions of the stat and stat64 structures */

struct target_stat {
    abi_ulong st_dev;
    abi_ulong st_ino;
    unsigned int st_mode;
    unsigned int st_nlink;
    unsigned int st_uid;
    unsigned int st_gid;
    abi_ulong st_rdev;
    abi_ulong __pad1;
    abi_long st_size;
    int st_blksize;
    int __pad2;
    abi_long st_blocks;
    abi_long target_st_atime;
    abi_ulong target_st_atime_nsec;
    abi_long target_st_mtime;
    abi_ulong target_st_mtime_nsec;
    abi_long target_st_ctime;
    abi_ulong target_st_ctime_nsec;
    unsigned int __unused4;
    unsigned int __unused5;
};

#if !defined(TARGET_RISCV64)
#define TARGET_HAS_STRUCT_STAT64
struct target_stat64 {
    uint64_t st_dev;
    uint64_t st_ino;
    unsigned int st_mode;
    unsigned int st_nlink;
    unsigned int st_uid;
    unsigned int st_gid;
    uint64_t st_rdev;
    uint64_t __pad1;
    int64_t st_size;
    int st_blksize;
    int __pad2;
    int64_t st_blocks;
    int target_st_atime;
    unsigned int target_st_atime_nsec;
    int target_st_mtime;
    unsigned int target_st_mtime_nsec;
    int target_st_ctime;
    unsigned int target_st_ctime_nsec;
    unsigned int __unused4;
    unsigned int __unused5;
};
#endif
```

**Comment by michaeljclark** [comment]
I'll try with the test case in https://github.com/riscv/riscv-gnu-toolchain/pull/325

**Comment by michaeljclark** [comment]
This code would have changed in the v1 patchset in December. For quite a while `riscv-next` was based on the 26-Sep-2016 rebase until we were satisfied that the forward port had enough testing. Obviously stat on rv32 slipped through the cracks.

**Comment by michaeljclark** [comment]
It could be a glibc bug

**Comment by michaeljclark** [comment]
Note: blksize_t and nlink_t are int and unsigned int on asm-generic, unlike aarch64. I had an issue with musl as its asm-generic was wrong and I had to override st_nlink and st_blksize. 

- https://github.com/rv8-io/musl-riscv/commit/c36f6d580ca58c0fa2e76dbaa5a61ac278d66bdf

The stat test works on musl rv32, however, it's likely always using stat64

```
mclark@minty:~/src/riscv-gcc-bugs$ /opt/riscv/musl-riscv-toolchain-7.2.0-7/bin/riscv32-linux-musl-gcc stat.c -static -o stat
mclark@minty:~/src/riscv-gcc-bugs$ /opt/riscv/qemu/bin/qemu-riscv32 stat
S_ISREG (buf.st_mode) = 0
```

**Comment by michaeljclark** [comment]
I have a feeling it may be a glibc bug, given we only define one stat structure. i.e. all stats should be 64-bit on rv32 because it is not a legacy architecture??

Need to find the glibc stat definition for rv32...

**Comment by michaeljclark** [comment]
The authoritative test is to run on riscv32 linux, not on the linux-user simulator, as the kernel is authoritative for asm-generic. Will try to get an rv32 kernel compiling...

**Comment by jim-wilson** [comment]
Yes, it could be a glibc problem.  Unfortunately the 32-bit glibc support was not upstreamed due to lack of time, and it isn't clear where the most up-to-date 32-bit glibc support is to be found.  I talked to Palmer about this briefly on Friday, and he indicated that he would try to find time to look at it.

**Comment by michaeljclark** [comment]
freedom-u-sdk doesn't require user-mode qemu nor does it use the riscv32 linux kernel, so it should be fine to bump riscv-qemu in freedom-u-sdk.

As long as we have the riscv32 stat bug raised somewhere e.g. PR https://github.com/riscv/riscv-gnu-toolchain/pull/325

**Comment by michaeljclark** [comment]
I think we need to run the riscv32 glibc stat test in riscv32 riscv-linux.

I raised PR https://github.com/riscv/riscv-pk/pull/85 to enabled HTIF console IO for riscv32 hosts in bbl, however we can use the riscv32 `virt` machine with `ns16550a` uart console for testing...

I will try to build riscv32 riscv-linux...

**Comment by michaeljclark** [comment]
I've change the commit to bump riscv-qemu in freedom-u-sdk to v8.2

@jim-wilson I don't think the riscv32 linux-user mode bug is relevant because freedom-u-sdk is using full system emulation. And until we have rv32 riscv-linux running, we can prove whether it is a glibc bug or a qemu bug.

@palmer-dabbelt it would nice to merge this so we can resolve issues that have been fixed, as the version in freedom-u-sdk is very old, relatively speaking, i.e. is based on the **9-Sep-2016** upstream sync before the forward port to latest qemu. v8 is the latest patch series sent upstream based on the *6-Mar-18* sync and has been pretty well-tested, including by the Fedora folk.

I don't think we should hold back updating to a more recent qemu. Lots of bugs have been fixed.

**Comment by michaeljclark** [comment]
Hang on... there might be a regression in SMP... One CPU is chewing 100% when running with `-smp cpus=4`. I'm going to have to bisect.

**Comment by michaeljclark** [comment]
However the current version linked in freedom-u-sdk doesn't have any SMP support at all.

**Comment by michaeljclark** [comment]
Cool. Thanks!

The SMP has been busy on one CPU since v5 when we merged Stefan's MTTCG patch. There might be an issue with WFI. I'll have to look into it. It's not a regression in terms of freedom-u-sdk, as that last version didn't have SMP.

**Comment by jim-wilson** [comment]
Agreed, the lack of 32-bit user support is more of a problem for riscv-gnu-toolchain where 32-bit support should presumably continue to work, and freedom-u-sdk has its own copy of qemu outside the riscv-gnu-toolchain package.

**Comment by michaeljclark** [comment]
Ya. We'll have to try to get rv32 riscv-linux running and/or verify the linux-headers to see what's happening for rv32 without LFS. RV32 should be LFS only? because its not a legacy port?

BTW - This means `freedom-u-dsk` is on the same commit we sent upstream to qemu which will hopefully be merged this week. Fingers-crossed.

**Comment by brucehoult** [comment]
@michaeljclark "The SMP has been busy on one CPU since v5 when we merged Stefan's MTTCG patch. There"

Are you sure about that? I was seeing only one line in top, but it was like 380%, so it's multiple cores getting busy in one process, no problems.

**Comment by michaeljclark** [comment]
I’m talking about on an idle system. Previously QEMU was between 2% to 6% on SMP when idle. We had this problem on uniprocessor before WFI was implemented. The cpu_has_work function changed radically in v5/v6 timeframe. The system shouldn’t use 100% cpu when idle.

**Comment by michaeljclark** [comment]
When I run without `-smp cpus=4` the qemu-system-riscv64 process idles at about 5% vs %100 when idle with SMP enabled. I'll raise an issue on riscv-qemu. Just checking with riscv-linux-4.15...

**Comment by brucehoult** [comment]
@michaeljclark oh! I didn't see the word "idle" in previous posts. As you were...

**Comment by michaeljclark** [comment]
It could be an MTTCG issue. I'm trying on a Linux host instead of macOS.

**Comment by michaeljclark** [comment]
Okay. It's likely a QEMU MTTCG issue on macOS. I have an idle 4 CPU instance of riscv-linux-4.15 running on a Debian Stretch Linux host, and it's only using 13% CPU while idle, which is much better than 100% CPU when idle (on macOS High Sierra 10.13.3)

Host

```
Linux minty 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux
```

Guest

```
Linux ucbvax 4.15.0-00050-g55f79e25d599 #97 SMP Sun Mar 4 09:23:30 NZDT 2018 riscv64 GNU/Linux
```

**Pull request merged**
