### PR TITLE
Allow users to set the ISA and ABI of the target machine

### PR DESCRIPTION
**Pull request by palmer-dabbelt**
While this is an SDK for the Freedom U platform, which right now is
RV64GC only, it's also where I've been pointing people who want to build
Linux and a userspace.  This patch allows users to change the ISA and
ABI of the target.

Most of the testing effort has been targeted towards RV64GC, but I think
it's good to let people try other targets (and then hopefully fix them
:)).

### CODE REVIEW

**Comment by palmer-dabbelt** [comment]
This should fix https://github.com/sifive/freedom-u-sdk/issues/16

**Comment by terpstra** [comment]
I tried:
make ISA=rv64ima ABI=lp64 sim
 and got:
[    0.130000] CPU: 1 PID: 1 Comm: init Not tainted 4.14.0-rc7-00028-g160fa84 #1
[    0.130000] task: ffffffe07da58000 task.stack: ffffffe07da36000

... oops?

**Comment by terpstra** [comment]
That's a pretty weird sepc.

**Comment by palmer-dabbelt** [comment]
Ugh...  I'm just going to merge this anyway -- at least the person who wanted no-C support should be safe here.  I probably just screwed something up with the FP detection code in BBL.

IDK what's up with that memory address...

**Pull request merged**
