### PR TITLE
use sifive branch to avoid going through issue #52 for vc707

### PR DESCRIPTION
**Pull request by mcd500**
I tried building the rootfs of SD card on vc707 and was fixing build breaks of buildroot. After I managed to fix them, I realize that I was just going though exactly the same track of issue #52 only with minor difference that I was using  v1.43.9 on e2fsprogs. So I decided to point to the branch which builds fine on Ubuntu 18.04.
I really appreciate for accepting my pull request for who would try the SD boot on vc707 and hoping more people to drag into risc-v. :)

### CODE REVIEW

**Comment by jim-wilson** [comment]
There is a big update in pr #88 that upgrades buildroot, the linux kernel, etc, and this builds fine on Ubuntu 18.04.  This was just merged in a few hours ago.  This presumably makes your pr unnecessary.

**Comment by mcd500** [comment]
Massive update with #88, great! It was in the middle of when I was making the build and pull requests. No wonder when I tried to create the pull request, there was a conflict.

I think there are two type of people who is using the freedom-u-sdk to create rootfs, one is who using the hard care such as HiFive Unleashed and the other is who is more focusing soft core on FPGA.

For the hard core, probably it will be good to have more rich and generic rootfs similar to debian and fedora for projects on keystone and etc. More rich rootfs will improve the productivity of software development on RV64.
For the soft core, the minimal rootfs for just booting from the sd card for testing and evaluating the core written on the FPGA would might suite better since it will have less time for building the sd boot image.

My pull request was for linux_u500vc707devkit_config branch only and I just wanted to have any kind of linux booting on Xilinx VC707. The freedom-u-sdk which just finishes build and boot successfully on vc707 was fine for me. The #88 only applied to the master branch and the linux_u500vc707devkit_config is left.

I just wanted to upload my revising after I came back from RISC-V workshop Taiwan and that is all.
Now it works fine with
---
git clone https://github.com/sifive/freedom-u-sdk
cd freedom-u-sdk
git checkout linux_u500vc707devkit_config
make -j4
---
and then `make DISK=/dev/whereissd format-boot-loader`.

**Comment by jim-wilson** [comment]
The freedom-u-sdk tree is not actively maintained.  You might consider switching to something better maintained like the riscv/meta-riscv tree for Open Embedded.

I don't do FPGA development.  We use Ubuntu 16.04 internally, and it works fine there.  I can't risk breaking the existing FPGA support, so I can't touch this.  And probably no one else will look at it.  I expect that this won't be fixed until SiFive upgrades to Ubuntu 18.04 internally.

**Comment by tmagik** [comment]
I may end up unofficial maintaining freedom-u-sdk just because I don't like
having to wait for bitbake.

If you have a vc707 and can update that Branch to work with the major
buildroot update in pr#88 I will definitely take a look and test it. I
would like to be able to support both fpga platforms and hifive-u from the
same Branch, and I suspect that will take some coordination with the
freedom repo to replace the fpga 'rom' bootloader with uboot

**Comment by mcd500** [comment]
@tmagik sure, I will try the #88 on vc707 and come back with you the feedback. I am also fine to be unofficially trying the testing the updates on vc707.
The vc707 is at the office. I am in middle of attending a conference and the next time I could test the image booting on the vc707 would be probably the after next week.

**Comment by tprrt** [comment]
This issue is no longer relevant.

**Pull request closed without merging**
