### PR TITLE
Merge priv-1.10 support to master

### PR DESCRIPTION
**Pull request by palmer-dabbelt**
We need to update the website image before merging this.

### CODE REVIEW

**Comment by richardxia** [comment]
Why do we need to make sure the website image is updated before merging this? People shouldn't just expect the tip of master to always be working with whatever image is on the site, right? We should probably tag releases of this repo that are known to work with an FPGA image.

We still run into the same problem if we bump the website image first, in that this repo's master branch won't work with the image.

**Comment by palmer-dabbelt** [comment]
I think we should submodule freedom-u-sdk and freedom-e-sdk into freedom.

**Comment by richardxia** [comment]
That makes sense to me, but we also have this other disconnect between the FPGA image on the website and what the latest `freedom` repo will generate. I think both website images are about a year old at this point, while `freedom` has continued to move on.

cc @mwachs5, since we probably want the same release strategy for the E platform.

**Comment by mwachs5** [comment]
The MCS images on the website are at least versioned.

We should also keep the Getting Started docs in mind, as they may or may not reference specific versions

**Pull request merged**
