### PR TITLE
Freedom-u-sdk major update

### PR DESCRIPTION
**Pull request by tmagik**
This set of changesets includes a couple of major updates:

1. Switch from riscv-gnu-toolchain to recent buildroot toolchain (reduces the size of a build dir from ~16G to ~10G)
2. include additional makefile targets for 'format-demo-image', 'format-boot-loader', 'flash-gpt' to more easily re-create the Debian desktop
3. U-boot pre-release and boot flow allowing editing of a uEnv.txt file to change kernel command line and boot device options

### CODE REVIEW

**Comment by jim-wilson** [comment]
My first build attempt fails with multiple errors.

  /home/jimw/tmp/freedom-u-sdk/linux/scripts/gen_initramfs_list.sh: Cannot open\
 '/home/jimw/tmp/freedom-u-sdk/work/buildroot_initramfs_sysroot'
Makefile:145: recipe for target '/home/jimw/tmp/freedom-u-sdk/work/initramfs.cp\
io.gz' failed
make: *** [/home/jimw/tmp/freedom-u-sdk/work/initramfs.cpio.gz] Error 1

Looks like the $(initramfs): rule needs a dependency on $(buildroot_initramfs_sysroot_stamp).

/bin/sh: 1: riscv64-buildroot-linux-gnu-gcc: not found
/bin/sh: 1: riscv64-buildroot-linux-gnu-gcc: not found
/home/jimw/tmp/freedom-u-sdk/HiFive_U-Boot/scripts/Makefile.autoconf:48: recipe\
 for target 'include/autoconf.mk.dep' failed
make[3]: *** [include/autoconf.mk.dep] Error 1

Looks like the $(uboot): rule needs a dependency on $(buildroot_initramfs_tar).

Just looking at the Makefile in general, there is a bunch of stuff that doesn't make sense.  You have a dependency on $(RISCV)/bin/$(target)-gcc but there is no rule to build that, so it isn't useful.  You have some left over code that checks for a RISCV environment variable in case the user provided one instead of building one, but that isn't supported anymore, so the env var check should go away.

There is a rule to build $(buildroot_initramfs_sysroot) which doesn't appear to do anything useful, as the rest of the Makefile actually uses $(buildroot_initramfs_sysroot_stamp) now.

There is a comment in format-demo-image that says disabled for now, but nothing in there is actually disabled.  I think you copied a disabled rule from format-boot-image into format-demo-image, and then re-enabled it, while forgetting to remove the comment that says it was disabled.

The documentation in README.md explaining how to set the switches is nice.

I see that we still have docs for spike, and we still have the riscv-fesvr and riscv-isa-sim submodules.  If we aren't going to support this, we may as well remove the spike docs and the two submodules.

**Comment by tmagik** [comment]
@jim-wilson did you run a parallel make, or did that happen with plain old make? I know some of the rules were slightly broken, I did not think they were that broken.,

Regarding spike, fesvr, and isa-sim, is there a way to test and confirm they still work? I'm hesitant to just drop it if it's easy to test.

**Comment by jim-wilson** [comment]
I pretty much always do parallel makes, as there are few single core machines anymore.

Like the README.me file says, "make sim" will try to boot linux on spike, but it won't work now because you are building bbl without the linux payload, which spike requires.  We would have to link two bbl images for this to work.  There may also be other reasons why it won't work.  spike is pretty limited in what it has support for.  If it hasn't been tested since the last linux kernel config file change, there is a good chance it won't work.  It may need its own config file and linux kernel build and/or initramfs build also.

**Comment by brucehoult** [comment]
I haven't tried this separate bbl and kernel thing, but is "cat" sufficient
to combine them?

**Comment by jim-wilson** [comment]
No,  If you need a combined bbl and kernel, then you need to link the kernel into bbl.  Otherwise, we get a dummy payload link into bbl that just prints a message saying it is a dummy payload.

**Comment by jim-wilson** [comment]
For some reason qemu won't build on my Ubuntu-18.04 laptop.
ERROR: glib-2.40 gthread-2.0 is required to compile QEMU
I have pkg-config and I have the right version of glib dev package installed, and "pkg-config --atleast-version=2.40 gthread-2.0" works when I run it by hand.  It just doesn't work when the configure script runs the command.  Weird.  I poked at it a while but I don't care enough to debug problems with the pkg-config command.

make sim fails as expected, printing 4 copies of the "this is a dummy payload" message, because we have 4 cores.

**Comment by jim-wilson** [comment]
I've built qemu on my laptop before.  It is just this qemu version that is refusing to build for an as yet unknown reason.

**Comment by jim-wilson** [comment]
OK, it is a Makefile bug.  Turns out that pkg-config has a nice --debug option.  The qemu build is failing because you unconditionally put the buildroot host/bin dir on the PATH, and this happens to have a pkg-config that only knows about packages that were built for buildroot.  We should not be using buildroot binaries when compiling stuff outside buildroot.

If I disable the PATH= line then qemu builds.  Curiously you have PATH=$PATH inside all of the buildroot rules which doesn't make much sense.  You don't have to set PATH if it was already set.  But it shouldn't be set globally, so the global one should be renamed and then the PATH= stuff in the buildroot rules will make sense.

So there is also an ordering issue here, as the qemu build only fails if you try to build it after building buildroot, otherwise the broken pkg-config isn't on your path.

Now that qemu builds, I get a linux kernel build failure.
Makefile.legacy:9: *** "You have legacy configuration in your .config! Please check your configuration.".  Stop.
Looks like you didn't update the config file used by the qemu build.  This needs to be fixed.

**Comment by jim-wilson** [comment]
The README.md doesn't mention that format-boot-loader requires sudo.  Though I do see a comment about adding udev rules to make this unecessary.  And the "make all" command does mention sudo, so not a major problem.

When I try format-boot-loader, I get an error
dd if=/home/jimw/tmp/freedom-u-sdk/work/HiFive_U-Boot/u-boot.bin of=/dev/sda3 bs=4096
dd: error writing '/dev/sda3': No space left on device
Partiion 3 is 400KB, but my u-boot.bin file is 464KB.
-rw-r--r-- 1 jimw jimw 464941 Mar 11 16:08 work/HiFive_U-Boot/u-boot.bin

I hacked around that, and then got
dd if=/home/jimw/tmp/freedom-u-sdk/work/hifive-unleashed-vfat.part of=/dev/sda1 bs=4096
dd: failed to open '/home/jimw/tmp/freedom-u-sdk/work/hifive-unleashed-vfat.part': No such file or directory
There are no dependencies on flash_image or vfat_image or flash_gpt and not clear why there are multiple rules for this.  Apparently I need boot-format-image to depend on $(vfat_image).

With that fixed I was able to run format-demo-image but it won't boot as there is no u-boot.bin on the SDcard as it didn't fit.

I see that the format-demo-image is ignoring errors for the copy of the demo image onto the sdcard, but if that gets an error, you won't have a valid demo image.  So ignoring the errors doesn't seem to  make any sense.

**Comment by tmagik** [comment]
> Partition 3 is 400KB, but my u-boot.bin file is 464KB.

So there's some sort of code size problem that bloated the u-boot binary that I don't understand just yet. Could switching from a default of 'lp64' to 'lp64d' result in that?

**Comment by jim-wilson** [comment]
With the latest updates, it builds OK.  There is still the problem that the u-boot binary is too big.  I don't have any reference to compare against, so I can't suggest what might have changed, other than point out the fact that you are using the buildroot compiler now which is probably related.  If you can give me something to compare against I may be able to provide a better answer.

qemu boots without a serial console.  I have to turn off CONFIG_VT to fix that.  I don't know why that works.  I just discovered that by trial and error when setting up my machine at home, and then forgot about it.  I had to look up the info to remember it.  I also need to enable CONFIG_HVC_RISCV_SBI for qemu which did not used to be necessary, but maybe that depends on which qemu branch you use.

Those same two config fixes allow sim to boot until it panics because there is no root.  We used to build an initram or something for that to work.  I'm less concerned about this though.  qemu working is more important.

**Comment by tmagik** [comment]
I’m going to guess we have to correctly set ‘console=</dev/sbiHVC>’, or whatever the name is, or find the patch that went into 4.15 that made it work right.

I added HVC_RISCV_SBI, but did not remote CONFIG_VT, as we need it for decent behavior with a graphics card.

**Pull request merged**
